module Paypal
  module Payment
    class Response
      # PAYMENTREQUEST_0_AMT
      # PAYMENTREQUEST_0_HANDLINGAMT
      # PAYMENTREQUEST_0_INSURANCEAMT
      # PAYMENTREQUEST_0_SHIPDISCAMT
      # PAYMENTREQUEST_0_SHIPPINGAMT
      # PAYMENTREQUEST_0_TAXAMT
      # PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED
      # PAYMENTREQUEST_0_CURRENCYCODE
      # PAYMENTREQUESTINFO_0_ERRORCODE
    end
  end
end
