module Paypal
  module Payment
    class Response
      # PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED
      # PAYMENTREQUEST_0_SHIPDISCAMT
      # PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE
      # PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME
      # PAYMENTREQUEST_0_CURRENCYCODE
      # PAYMENTREQUEST_0_SHIPTOSTATE
      # PAYMENTREQUEST_0_TAXAMT
      # PAYMENTREQUEST_0_SHIPTOCITY
      # PAYMENTREQUEST_0_INSURANCEAMT
      # PAYMENTREQUEST_0_SHIPPINGAMT
      # PAYMENTREQUEST_0_SHIPTONAME
      # PAYMENTREQUEST_0_HANDLINGAMT
      # PAYMENTREQUEST_0_SHIPTOZIP
      # PAYMENTREQUEST_0_AMT
      # PAYMENTREQUEST_0_SHIPTOSTREET
      # PAYMENTREQUESTINFO_0_ERRORCODE
    end
  end
end
